server:
    servlet:
        context-path: /funvirtualreading/api

spring:
    profiles:
        active: dev
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER 
        
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/fun_virtual_reading
        username: root
        password: adminRoot_123
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                '[format_sql]': true
        show-sql: true

server:
    port: 9080
---
spring:
    config:
        activate:
            on-profile: pdn
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: ${PORT}